import {
  Activity,
  BookOpen,
  AirVent,
  ArrowRightLeft,
  CalendarCheck,
  CircleDashed,
  CirclePause,
  CirclePlay,
  DoorClosed,
  FastForward,
  Gpu,
  GraduationCap,
  Heater,
  History,
  Leaf,
  LoaderCircle,
  Microchip,
  Package,
  Recycle,
  ServerCog,
  Waypoints,
  Wind,
  CircleCheck,
  CircleDollarSign,
  CircleQuestionMark,
  CircleX,
  Clock,
  Construction,
  Cpu,
  Flame,
  HardHat,
  House,
  Info,
  Keyboard,
  Map as MapIcon,
  Move,
  Cable,
  Network,
  Pause,
  Play,
  PlugZap,
  RotateCcw,
  Server,
  Snowflake,
  Target,
  Thermometer,
  Trash,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Trophy,
  UserPlus,
  Wrench,
  X,
  Zap,
  ChevronDown,
  ChevronUp,
  Menu,
  Settings,
  Bug,
  Save,
  FolderOpen,
  Download,
  Upload,
  Volume2,
  Monitor,
  Eye,
  LogOut,
  ChartLine,
  Layers,
  FlaskConical,
  Award,
  BatteryCharging,
  Fuel,
  Lock,
  Droplets,
  RotateCw,
  ThermometerSun,
  type IconNode,
} from 'lucide';

/** Toutes les icônes du HUD, par rôle : changer une icône se fait ici, une seule fois. */
export const ICONS = {
  money: CircleDollarSign,
  trendUp: TrendingUp,
  trendDown: TrendingDown,
  power: Zap,
  compute: Cpu,
  temperature: Thermometer,
  team: HardHat,
  time: Clock,
  pause: Pause,
  play: Play,
  rack: Server,
  crac: Snowflake,
  pdu: PlugZap,
  demolish: Trash,
  hire: UserPlus,
  heatmap: Flame,
  edgePan: Move,
  minimap: MapIcon,
  help: CircleQuestionMark,
  book: BookOpen,
  keyboard: Keyboard,
  alert: TriangleAlert,
  repair: Wrench,
  build: Construction,
  done: CircleCheck,
  failed: CircleX,
  info: Info,
  target: Target,
  trophy: Trophy,
  restart: RotateCcw,
  home: House,
  close: X,
  expand: ChevronDown,
  collapse: ChevronUp,
  menu: Menu,
  settings: Settings,
  bug: Bug,
  save: Save,
  load: FolderOpen,
  download: Download,
  upload: Upload,
  volume: Volume2,
  display: Monitor,
  accessibility: Eye,
  quit: LogOut,
  dashboard: ChartLine,
  layers: Layers,
  research: FlaskConical,
  tier: Award,
  ups: BatteryCharging,
  generator: Fuel,
  lock: Lock,
  cdu: Droplets,
  rotate: RotateCw,
  weather: ThermometerSun,
  switch: Network,
  cable: Cable,
  // Recherche : une icône par nœud (ui/catalog.ts › RESEARCH_ICON) et les pictogrammes d'état des tuiles.
  recycle: Recycle,
  gpu: Gpu,
  retrofit: ServerCog,
  checkpoint: History,
  chip: Microchip,
  fabric: Waypoints,
  airflow: AirVent,
  containment: DoorClosed,
  wind: Wind,
  heatReuse: Heater,
  green: Leaf,
  switchover: ArrowRightLeft,
  fastTechs: FastForward,
  planned: CalendarCheck,
  spareParts: Package,
  specialties: GraduationCap,
  predictive: Activity,
  launch: CirclePlay,
  paused: CirclePause,
  running: LoaderCircle,
  pending: CircleDashed,
} satisfies Record<string, IconNode>;

export type IconName = keyof typeof ICONS;
