import {
  CircleCheck,
  CircleDollarSign,
  CircleQuestionMark,
  CircleX,
  Clock,
  Construction,
  Cpu,
  Flame,
  HardHat,
  House,
  Info,
  Keyboard,
  Map as MapIcon,
  Move,
  Network,
  Pause,
  Play,
  PlugZap,
  RotateCcw,
  Server,
  Snowflake,
  Target,
  Thermometer,
  Trash,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Trophy,
  UserPlus,
  Wrench,
  X,
  Zap,
  ChevronDown,
  ChevronUp,
  Menu,
  Settings,
  Bug,
  Save,
  FolderOpen,
  Download,
  Upload,
  Volume2,
  Monitor,
  Eye,
  LogOut,
  ChartLine,
  Layers,
  FlaskConical,
  Award,
  BatteryCharging,
  Fuel,
  Lock,
  Droplets,
  RotateCw,
  ThermometerSun,
  type IconNode,
} from 'lucide';

/** Toutes les icônes du HUD, par rôle : changer une icône se fait ici, une seule fois. */
export const ICONS = {
  money: CircleDollarSign,
  trendUp: TrendingUp,
  trendDown: TrendingDown,
  power: Zap,
  compute: Cpu,
  temperature: Thermometer,
  team: HardHat,
  time: Clock,
  pause: Pause,
  play: Play,
  rack: Server,
  crac: Snowflake,
  pdu: PlugZap,
  demolish: Trash,
  hire: UserPlus,
  heatmap: Flame,
  edgePan: Move,
  minimap: MapIcon,
  help: CircleQuestionMark,
  keyboard: Keyboard,
  alert: TriangleAlert,
  repair: Wrench,
  build: Construction,
  done: CircleCheck,
  failed: CircleX,
  info: Info,
  target: Target,
  trophy: Trophy,
  restart: RotateCcw,
  home: House,
  close: X,
  expand: ChevronDown,
  collapse: ChevronUp,
  menu: Menu,
  settings: Settings,
  bug: Bug,
  save: Save,
  load: FolderOpen,
  download: Download,
  upload: Upload,
  volume: Volume2,
  display: Monitor,
  accessibility: Eye,
  quit: LogOut,
  dashboard: ChartLine,
  layers: Layers,
  research: FlaskConical,
  tier: Award,
  ups: BatteryCharging,
  generator: Fuel,
  lock: Lock,
  cdu: Droplets,
  rotate: RotateCw,
  weather: ThermometerSun,
  switch: Network,
} satisfies Record<string, IconNode>;

export type IconName = keyof typeof ICONS;
