import {
  CircleCheck,
  CircleDollarSign,
  CircleQuestionMark,
  CircleX,
  Clock,
  Construction,
  Cpu,
  Flame,
  HardHat,
  House,
  Info,
  Keyboard,
  Map as MapIcon,
  Move,
  Pause,
  Play,
  PlugZap,
  RotateCcw,
  Server,
  Snowflake,
  Target,
  Thermometer,
  Trash,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Trophy,
  UserPlus,
  Wrench,
  X,
  Zap,
  ChevronDown,
  ChevronUp,
  type IconNode,
} from 'lucide';

/** Toutes les icônes du HUD, par rôle : changer une icône se fait ici, une seule fois. */
export const ICONS = {
  money: CircleDollarSign,
  trendUp: TrendingUp,
  trendDown: TrendingDown,
  power: Zap,
  compute: Cpu,
  temperature: Thermometer,
  team: HardHat,
  time: Clock,
  pause: Pause,
  play: Play,
  rack: Server,
  crac: Snowflake,
  pdu: PlugZap,
  demolish: Trash,
  hire: UserPlus,
  heatmap: Flame,
  edgePan: Move,
  minimap: MapIcon,
  help: CircleQuestionMark,
  keyboard: Keyboard,
  alert: TriangleAlert,
  repair: Wrench,
  build: Construction,
  done: CircleCheck,
  failed: CircleX,
  info: Info,
  target: Target,
  trophy: Trophy,
  restart: RotateCcw,
  home: House,
  close: X,
  expand: ChevronDown,
  collapse: ChevronUp,
} satisfies Record<string, IconNode>;

export type IconName = keyof typeof ICONS;
